export const CORE_WORKSPACE_MODE = 'core-foundation'
export const CORE_WORKSPACE_VERSION = '0.1.0'

export * from '@/core/ai'
export * from '@/core/config'
export * from '@/core/rules'
export * from '@/core/scoring'
export * from '@/core/testing/ruleCase'
export * from '@/core/testing/roundScenario'
export * from '@/core/types'
export * from '@/core/wall'
